#  List of git-hooks, during during committing files to git repo

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
        - id: java-formatter
          name: java-formatter
          entry: style-guide/inspect-java-format-0.1.sh
          language: script
          files: '\.java$'
          stages: [commit]
# Golang checks
-   repo: https://github.com/dnephin/pre-commit-golang.git
    rev: "v0.4.0"
    hooks:
        - id: go-imports
        - id: go-fmt
        #- id: golangci-lint TODO




