#!/usr/bin/env bash

set -euxo pipefail
# Sonar Server URL
SONAR_HOST_URL=10.87.78.247:80
# Sonar sever login token for the project
SONAR_LOGIN="2f76b79f36027e018ecd699fccdbbdd0c9d1766e"
# path of the repo which needs to be scanned
REPO=$PWD/src
# run sonar-cli as a docker container and publish results to the sonar server
docker run \
    --rm \
    -e SONAR_HOST_URL="http://${SONAR_HOST_URL}" \
    -e SONAR_LOGIN=$SONAR_LOGIN \
    -v "${REPO}:/usr/src" \
    sonarsource/sonar-scanner-cli
